// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEmp = "emp"

// Emp mapped from table <emp>
type Emp struct {
	ID       int32  `gorm:"column:id;primaryKey" json:"id"`
	Name     string `gorm:"column:name" json:"name"`
	Age      int32  `gorm:"column:age" json:"age"`
	Addresss string `gorm:"column:addresss" json:"addresss"`
}

// TableName Emp's table name
func (*Emp) TableName() string {
	return TableNameEmp
}
